import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { SignInButton, useUser } from "@clerk/nextjs";

const CreatePostWizard = () => {
    const { user } = useUser();
    if (!user) {
        return null;
    }

    return <div className="flex gap-3 w-full">
        <img src={user.profileImageUrl} alt="Profile image" className="w-14 h-14 rounded-full" />
        <input placeholder="Type some emojis!" className="bg-transparent grow outline-none" />
    </div>
};

export default function Home() {
    const user = useUser();
    const { data } = api.posts.getAll.useQuery();

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex justify-center h-screen">
                <div className="border-x border-slate-400 w-full md:max-w-2xl">
                    <div className="flex border-b border-slate-400 p-4">
                        {!user.isSignedIn && (
                            <div className="flex justify-center">
                                <SignInButton />
                            </div>
                        )}
                        {user.isSignedIn && <CreatePostWizard />}
                    </div>
                    <div className="flex flex-col">
                        {data?.map((post) => (
                            <div key={post.id} className="p-8 border-b border-slate-400">{post.content}</div>
                        ))}
                    </div>
                </div>
            </main>
        </>
    );
}
